#%RAML 1.0
version: v1
title: Salesforce CRM API

types:
  Contact: !include exchange_modules/b43e4e64-3308-45f1-9599-bc9bc78957e6/contact/1.0.1/contact.raml

/contact:
  get:
    queryParameters:
      id: string
    responses:
      200:
        description: Return contact details
        body:
          application/json:
            type: Contact