#%RAML 1.0
version: v1
title: Salesforce CRM API

types:
  Contact: !include exchange_modules/82f78ed0-714c-47f0-b038-c0c1c061d2f3/contact/1.0.0/contact.raml

/contacts:
  get:
    queryParameters:
      changedSince: 
        type: datetime-only
        example: 2015-07-04T21:00:00
    responses:
      200:
        description: Returns all new or modifed contact details after changed since parameter
        body:
          application/json:
            type: Contact []

/contacts/{id}:
  get:
    responses:
      200:
        description: Return contact details
        body:
          application/json:
            type: Contact