#%RAML 1.0
version: v1
title: Salesforce CRM API

types:
  Contact: !include exchange_modules/42d8e488-c27a-40fa-981c-359a73641d4f/contact/1.0.0/contact.raml

traits:
  client-id-required:
    queryParameters:
      client_id:
        type: string
      client_secret:
        type: string

/contacts:
  get:
    is: [client-id-required]
    queryParameters:
      changedSince: 
        type: datetime-only
        example: 2015-07-04T21:00:00
    responses:
      200:
        description: Returns all new or modifed contact details after changed since parameter
        body:
          application/json:
            type: Contact []

/contacts/{id}:
  get:
    is: [client-id-required]
    responses:
      200:
        description: Return contact details
        body:
          application/json:
            type: Contact